// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYxSFniJyBACgEtLX_47E7X7n4-BxYMUM',
    appId: '1:909144116642:web:c810ede81230a7d13a36fb',
    messagingSenderId: '909144116642',
    projectId: 'mealkingresturant',
    authDomain: 'mealkingresturant.firebaseapp.com',
    storageBucket: 'mealkingresturant.appspot.com',
    measurementId: 'G-6BF865Z1C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDusFRT7SS839bfyhrro4noZDOb9OoHHgo',
    appId: '1:909144116642:android:fd49430fabb5266d3a36fb',
    messagingSenderId: '909144116642',
    projectId: 'mealkingresturant',
    storageBucket: 'mealkingresturant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkw3qO4Y2gckKXvJ43Rp-A_lIvzkMnuF0',
    appId: '1:909144116642:ios:10b20b39fec7382c3a36fb',
    messagingSenderId: '909144116642',
    projectId: 'mealkingresturant',
    storageBucket: 'mealkingresturant.appspot.com',
    iosBundleId: 'com.example.syflexMealmatesResturant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkw3qO4Y2gckKXvJ43Rp-A_lIvzkMnuF0',
    appId: '1:909144116642:ios:27b54288324f6e793a36fb',
    messagingSenderId: '909144116642',
    projectId: 'mealkingresturant',
    storageBucket: 'mealkingresturant.appspot.com',
    iosBundleId: 'com.example.syflexMealmatesResturant.RunnerTests',
  );
}
