// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBsXlwTbCu9RHNhIkcI5chFDvKKIArnaQ',
    appId: '1:446249553608:web:b6e7da3367f6cee7a69ffd',
    messagingSenderId: '446249553608',
    projectId: 'mealking-7368c',
    authDomain: 'mealking-7368c.firebaseapp.com',
    storageBucket: 'mealking-7368c.appspot.com',
    measurementId: 'G-Z1CBVS4XRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOrPQHqImSd3QqUVbslJZb5t2aO7JXTr4',
    appId: '1:446249553608:android:daa6bd01fdedec65a69ffd',
    messagingSenderId: '446249553608',
    projectId: 'mealking-7368c',
    storageBucket: 'mealking-7368c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfptOkprhQVQ3RE_ucS7JhBkYOxTZxyJk',
    appId: '1:446249553608:ios:8861d0b059b9e441a69ffd',
    messagingSenderId: '446249553608',
    projectId: 'mealking-7368c',
    storageBucket: 'mealking-7368c.appspot.com',
    iosBundleId: 'com.example.syflexMeamates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfptOkprhQVQ3RE_ucS7JhBkYOxTZxyJk',
    appId: '1:446249553608:ios:9e9274996faba501a69ffd',
    messagingSenderId: '446249553608',
    projectId: 'mealking-7368c',
    storageBucket: 'mealking-7368c.appspot.com',
    iosBundleId: 'com.example.syflexMeamates.RunnerTests',
  );
}
