// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Ud88YzilXAn5PztCN1GcaDMCLetogt8',
    appId: '1:216645722799:web:1ba13998703c33885eea5a',
    messagingSenderId: '216645722799',
    projectId: 'mealkinguser',
    authDomain: 'mealkinguser.firebaseapp.com',
    storageBucket: 'mealkinguser.appspot.com',
    measurementId: 'G-P9ML3868KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0WypzziEv20iNFxMESjpu235dpCKT1Gk',
    appId: '1:216645722799:android:97ec5baf0ae2dc305eea5a',
    messagingSenderId: '216645722799',
    projectId: 'mealkinguser',
    storageBucket: 'mealkinguser.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaIX2GhUksj5l6kBelxgw6udox8KICHmk',
    appId: '1:216645722799:ios:fe0b39aa8dd3813c5eea5a',
    messagingSenderId: '216645722799',
    projectId: 'mealkinguser',
    storageBucket: 'mealkinguser.appspot.com',
    iosBundleId: 'com.example.syflexMealmatessUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaIX2GhUksj5l6kBelxgw6udox8KICHmk',
    appId: '1:216645722799:ios:9f462bad8906f1b25eea5a',
    messagingSenderId: '216645722799',
    projectId: 'mealkinguser',
    storageBucket: 'mealkinguser.appspot.com',
    iosBundleId: 'com.example.syflexMealmatessUser.RunnerTests',
  );
}
